clear;
clc;
f = @(x,u) -sin(x) + 1.2.* u;
fhat = @(xhat,u) -sin(xhat) + 1.* u;
A = @(xhat) -cos(xhat);
C = 1;
Q = 1;
R = 5;
dP = @(P,xhat) A(xhat)*P+P*A(xhat)'+Q-P*C'/R*C*P;
H = @(P) P*C'/R;
xhatdot = @(xhat,P,u,y) fhat(xhat,u)+H(P)*(y-xhat);
F = @(x,xhat,P,u,y)[f(x,u);xhatdot(xhat,P,u,y);dP(P,xhat)];
x0 = 1;
P0 = 1;
xhat0 = 0;
X0 = [x0;xhat0;P0];
tfinal = 20;
w = @(t) 0.2*sin(10*t);
u = @(t) sin(t);
ode45(@(t,z)F(z(1,:),z(2,:),z(3,:),u(t),z(1,:)+w(t)),[0,tfinal],X0);
